#!/bin/bash
# Script to submit PhotonSim jobs with UNIFORM energy distribution + LUCiD processing
# Usage: ./submit_photonsim_lucid_job_uniform.sh -p <particle> -n <nevents> -m <min_energy> -M <max_energy> -o <output_dir> [-f <filename>] [-l <lucid_path>]

# Default values
PARTICLE="mu-"
NEVENTS=100
MIN_ENERGY=210
MAX_ENERGY=1500
OUTPUT_DIR=""
OUTPUT_FILE="output.root"
LUCID_PATH="/sdf/home/c/cjesus/Dev/LUCiD"

# Get the directory where this script is located
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
PHOTONSIM_DIR="$( cd "${SCRIPT_DIR}/../.." && pwd )"
UTILS_DIR="${SCRIPT_DIR}/../utils"
USER_PATHS="${SCRIPT_DIR}/../user_paths.sh"

# Source user paths
if [ -f "${USER_PATHS}" ]; then
    source "${USER_PATHS}"
else
    echo "Error: user_paths.sh not found at ${USER_PATHS}"
    exit 1
fi

# Parse command line arguments
while getopts "p:n:m:M:o:f:l:h" opt; do
    case $opt in
        p) PARTICLE="$OPTARG";;
        n) NEVENTS="$OPTARG";;
        m) MIN_ENERGY="$OPTARG";;
        M) MAX_ENERGY="$OPTARG";;
        o) OUTPUT_DIR="$OPTARG";;
        f) OUTPUT_FILE="$OPTARG";;
        l) LUCID_PATH="$OPTARG";;
        h) echo "Usage: $0 -p <particle> -n <nevents> -m <min_energy> -M <max_energy> -o <output_dir> [-f <filename>] [-l <lucid_path>]"
           echo "  -p: Particle type (default: mu-)"
           echo "  -n: Number of events (default: 100)"
           echo "  -m: Minimum energy in MeV (default: 210)"
           echo "  -M: Maximum energy in MeV (default: 1500)"
           echo "  -o: Output directory (required)"
           echo "  -f: Output filename (default: output.root)"
           echo "  -l: LUCiD installation path (default: /sdf/home/c/cjesus/Dev/LUCiD)"
           exit 0;;
        \?) echo "Invalid option -$OPTARG" >&2; exit 1;;
    esac
done

# Check required parameters
if [ -z "$OUTPUT_DIR" ]; then
    echo "Error: Output directory is required (-o option)"
    exit 1
fi

# Convert energies to integers for directory name
MIN_ENERGY_INT=$(printf "%.0f" $MIN_ENERGY)
MAX_ENERGY_INT=$(printf "%.0f" $MAX_ENERGY)

# Create full output path: output_dir/particle_type/minE_maxE_MeV_uniform/
FULL_OUTPUT_DIR="${OUTPUT_DIR}/${PARTICLE}/${MIN_ENERGY_INT}_${MAX_ENERGY_INT}MeV_uniform"
echo "Creating output directory: ${FULL_OUTPUT_DIR}"
mkdir -p "${FULL_OUTPUT_DIR}"

# Create the macro file
MACRO_FILE="${FULL_OUTPUT_DIR}/run_${PARTICLE}_${MIN_ENERGY_INT}_${MAX_ENERGY_INT}MeV_uniform_${NEVENTS}events_${OUTPUT_FILE%.root}.mac"
echo "Creating macro file: ${MACRO_FILE}"

cat > "${MACRO_FILE}" << EOF
# PhotonSim macro for ${PARTICLE} with UNIFORM energy ${MIN_ENERGY}-${MAX_ENERGY} MeV
# Generated by submit_photonsim_lucid_job_uniform.sh
# Individual photon storage ENABLED

# Set output filename before initialization
/output/filename ${OUTPUT_FILE}

/run/initialize

# ENABLE individual photon/edep storage for event-by-event analysis
/photon/storeIndividual true
/edep/storeIndividual true

# Disable muon decay processes via macro commands
/particle/select mu-
/particle/process/inactivate 1
/particle/process/inactivate 7
/particle/select mu+
/particle/process/inactivate 1

# Disable pion decay processes via macro commands
/particle/select pi+
/particle/process/inactivate 1
/particle/select pi-
/particle/process/inactivate 1

# Set up primary particle with UNIFORM RANDOM energy
/gun/particle ${PARTICLE}
/gun/randomEnergy true
/gun/energyMin ${MIN_ENERGY} MeV
/gun/energyMax ${MAX_ENERGY} MeV
/gun/position 0 0 0 m
/gun/direction 0 0 1

# Run ${NEVENTS} events
/run/beamOn ${NEVENTS}
EOF

# Create the job execution script
JOB_SCRIPT="${FULL_OUTPUT_DIR}/run_photonsim_lucid_${OUTPUT_FILE%.root}.sh"
echo "Creating job script: ${JOB_SCRIPT}"

# Extract job ID from filename (e.g., output_job001.root -> 001)
JOB_ID=$(echo "${OUTPUT_FILE}" | sed -n 's/.*job\([0-9]*\)\.root/\1/p')
if [ -z "$JOB_ID" ]; then
    JOB_ID="000"
fi

cat > "${JOB_SCRIPT}" << 'EOFSCRIPT'
#!/bin/bash
# PhotonSim + LUCiD job execution script
# Generated by submit_photonsim_lucid_job_uniform.sh

echo "Starting PhotonSim + LUCiD job (UNIFORM ENERGY, INDIVIDUAL PHOTON STORAGE)"
echo "Particle: PARTICLE_PLACEHOLDER"
echo "Energy range: MIN_ENERGY_PLACEHOLDER-MAX_ENERGY_PLACEHOLDER MeV (uniform distribution)"
echo "Events: NEVENTS_PLACEHOLDER"
echo "Output: OUTPUT_FILE_PLACEHOLDER"

# Source environment
source UTILS_DIR_PLACEHOLDER/setup_environment.sh

# Change to output directory
cd FULL_OUTPUT_DIR_PLACEHOLDER

# Step 1: Run PhotonSim
echo ""
echo "=== Step 1: Running PhotonSim ==="
PHOTONSIM_DIR_PLACEHOLDER/build/PhotonSim MACRO_FILE_PLACEHOLDER

# Check if output file was created
if [ -f "OUTPUT_FILE_PLACEHOLDER" ]; then
    echo "Success! PhotonSim output file created: OUTPUT_FILE_PLACEHOLDER"
    ls -lh OUTPUT_FILE_PLACEHOLDER
else
    echo "Error: PhotonSim output file not created"
    exit 1
fi

# Step 2: Set up LUCiD environment
echo ""
echo "=== Step 2: Setting up LUCiD environment ==="
export SINGULARITY_IMAGE_PATH=/sdf/group/neutrino/images/develop.sif
function spython() {
    singularity exec --nv -B /sdf,/fs,/sdf/scratch,/lscratch ${SINGULARITY_IMAGE_PATH} python "$@"
}

# Create output folder for LUCiD
LUCID_OUTPUT_FOLDER="FULL_OUTPUT_DIR_PLACEHOLDER/folder_jobJOB_ID_PLACEHOLDER"
mkdir -p "${LUCID_OUTPUT_FOLDER}"
echo "Created LUCiD output folder: ${LUCID_OUTPUT_FOLDER}"

# Step 3: Run LUCiD
echo ""
echo "=== Step 3: Running LUCiD ==="
PHOTONSIM_OUTPUT="FULL_OUTPUT_DIR_PLACEHOLDER/OUTPUT_FILE_PLACEHOLDER"
echo "Input: ${PHOTONSIM_OUTPUT}"
echo "Output folder: ${LUCID_OUTPUT_FOLDER}"

spython LUCID_PATH_PLACEHOLDER/tools/production/generate_events.py \
    --input "${PHOTONSIM_OUTPUT}" \
    --particle-type PARTICLE_PLACEHOLDER \
    --output "${LUCID_OUTPUT_FOLDER}"

# Check if LUCiD output was created
LUCID_OUTPUT_FILE="${LUCID_OUTPUT_FOLDER}/merged_events.h5"
if [ -f "${LUCID_OUTPUT_FILE}" ]; then
    echo "Success! LUCiD output file created: ${LUCID_OUTPUT_FILE}"
    ls -lh "${LUCID_OUTPUT_FILE}"
else
    echo "Error: LUCiD output file not created"
    exit 1
fi

# Step 4: Rename and move the .h5 file
echo ""
echo "=== Step 4: Organizing output files ==="
FINAL_H5_NAME="events_jobJOB_ID_PLACEHOLDER.h5"
FINAL_H5_PATH="FULL_OUTPUT_DIR_PLACEHOLDER/${FINAL_H5_NAME}"

mv "${LUCID_OUTPUT_FILE}" "${FINAL_H5_PATH}"
echo "Moved and renamed: ${LUCID_OUTPUT_FILE} -> ${FINAL_H5_PATH}"
ls -lh "${FINAL_H5_PATH}"

# Remove the temporary folder
rmdir "${LUCID_OUTPUT_FOLDER}" 2>/dev/null && echo "Removed temporary folder: ${LUCID_OUTPUT_FOLDER}" || echo "Folder not empty, keeping: ${LUCID_OUTPUT_FOLDER}"

echo ""
echo "=== Job completed successfully ==="
echo "PhotonSim output: FULL_OUTPUT_DIR_PLACEHOLDER/OUTPUT_FILE_PLACEHOLDER"
echo "LUCiD output: ${FINAL_H5_PATH}"
EOFSCRIPT

# Replace placeholders in the script
sed -i "s|PARTICLE_PLACEHOLDER|${PARTICLE}|g" "${JOB_SCRIPT}"
sed -i "s|MIN_ENERGY_PLACEHOLDER|${MIN_ENERGY}|g" "${JOB_SCRIPT}"
sed -i "s|MAX_ENERGY_PLACEHOLDER|${MAX_ENERGY}|g" "${JOB_SCRIPT}"
sed -i "s|NEVENTS_PLACEHOLDER|${NEVENTS}|g" "${JOB_SCRIPT}"
sed -i "s|OUTPUT_FILE_PLACEHOLDER|${OUTPUT_FILE}|g" "${JOB_SCRIPT}"
sed -i "s|UTILS_DIR_PLACEHOLDER|${UTILS_DIR}|g" "${JOB_SCRIPT}"
sed -i "s|FULL_OUTPUT_DIR_PLACEHOLDER|${FULL_OUTPUT_DIR}|g" "${JOB_SCRIPT}"
sed -i "s|PHOTONSIM_DIR_PLACEHOLDER|${PHOTONSIM_DIR}|g" "${JOB_SCRIPT}"
sed -i "s|MACRO_FILE_PLACEHOLDER|${MACRO_FILE}|g" "${JOB_SCRIPT}"
sed -i "s|LUCID_PATH_PLACEHOLDER|${LUCID_PATH}|g" "${JOB_SCRIPT}"
sed -i "s|JOB_ID_PLACEHOLDER|${JOB_ID}|g" "${JOB_SCRIPT}"

chmod +x "${JOB_SCRIPT}"

# Create the SLURM submission script
SLURM_SCRIPT="${FULL_OUTPUT_DIR}/submit_job_lucid_${OUTPUT_FILE%.root}.sbatch"
echo "Creating SLURM submission script: ${SLURM_SCRIPT}"

# Create job name with particle, energy range, and timestamp
JOB_NAME="photonsim_lucid_${PARTICLE}_${MIN_ENERGY_INT}-${MAX_ENERGY_INT}MeV_$(date +%Y%m%d_%H%M%S)"

cat > "${SLURM_SCRIPT}" << EOF
#!/bin/bash
#SBATCH --partition=${SLURM_PARTITION}
#SBATCH --account=${SLURM_ACCOUNT}
#
#SBATCH --job-name=${JOB_NAME}
#SBATCH --output=${FULL_OUTPUT_DIR}/job_lucid_${OUTPUT_FILE%.root}-%j.out
#SBATCH --error=${FULL_OUTPUT_DIR}/job_lucid_${OUTPUT_FILE%.root}-%j.err
#
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=${DEFAULT_CPUS}
#SBATCH --mem-per-cpu=${DEFAULT_MEMORY}
#
#SBATCH --time=${DEFAULT_TIME}

echo "SLURM Job ID: \${SLURM_JOB_ID}"
echo "Job started at: \$(date)"
echo "Running on node: \$(hostname)"
echo "Working directory: \$(pwd)"

# Execute the job script
${JOB_SCRIPT}

echo "Job ended at: \$(date)"
EOF

chmod +x "${SLURM_SCRIPT}"

# Summary
echo ""
echo "=== Job preparation complete ==="
echo "Output directory: ${FULL_OUTPUT_DIR}"
echo "Macro file: ${MACRO_FILE}"
echo "Job script: ${JOB_SCRIPT}"
echo "SLURM script: ${SLURM_SCRIPT}"
echo ""
echo "This job will:"
echo "  1. Run PhotonSim to generate ${OUTPUT_FILE}"
echo "  2. Run LUCiD to process the ROOT file"
echo "  3. Create events_job${JOB_ID}.h5 in the output directory"
echo ""
echo "To submit this job, run:"
echo "  sbatch ${SLURM_SCRIPT}"
echo ""
echo "To test locally first, run:"
echo "  ${JOB_SCRIPT}"
