#!/usr/bin/env python3
"""Scan PhotonSim across a (particle, energy) grid for a fixed material.

Drives PhotonSim via Docker (the canonical macOS path documented in
INTERM/CLAUDE.md) and writes one ROOT file per cell, intended as input to
the s_max(E, particle, material) parametrisation for the SIREN refactor.

Output layout (host paths):

    <output-dir>/<material>/<particle>/<energy>MeV/
        run.mac
        photonsim.root
        stdout.log

Inside the container, the host <output-dir> is bind-mounted at /out, so the
macro's /output/filename points at /out/<material>/<particle>/<E>MeV/photonsim.root.
"""

from __future__ import annotations

import argparse
import shutil
import subprocess
import sys
from pathlib import Path


PARTICLES_KNOWN = {"mu-", "mu+", "e-", "e+", "pi+", "pi-", "gamma", "proton"}

# PhotonSim's DetectorConstruction currently hardcodes water at init time;
# no material messenger exists yet. The script still treats material as a
# CLI argument so the output tree is already keyed on it — when a material
# messenger lands later, allow the corresponding name here.
MATERIALS_KNOWN = {"water"}

DEFAULT_ENERGIES_MEV = [10, 100, 200, 500, 1000, 2000, 5000, 10000, 50000]

DEFAULT_EVENT_FLOOR = 10
DEFAULT_EVENT_BASE = 100        # events used at and below the anchor energy
DEFAULT_EVENT_ANCHOR_MEV = 1000  # halve events per doubling above this


def default_events_for(energy_mev: int) -> int:
    """Energy-dependent event count.

    Flat at DEFAULT_EVENT_BASE (=100) at and below the anchor (=1 GeV);
    halved per doubling above; floored at DEFAULT_EVENT_FLOOR (=10).
    """
    if energy_mev <= DEFAULT_EVENT_ANCHOR_MEV:
        return DEFAULT_EVENT_BASE
    raw = DEFAULT_EVENT_BASE * DEFAULT_EVENT_ANCHOR_MEV / energy_mev
    return max(DEFAULT_EVENT_FLOOR, int(round(raw)))


def _decay_disable_block(particle: str) -> str:
    """Disable Decay (and mu- capture-at-rest) to match the existing SIREN
    training macros under tools/t0_correction/energy_scan_macros/. Without
    this, low-E mu- that stop inside the volume produce a ~50 MeV decay
    electron whose Cherenkov inflates s_max relative to SIREN's training set.

    Process indices are hardcoded to match the existing macros — they refer
    to slots in PhotonSim's physics-list process manager, not portable.
    Currently only muons are handled; other particles fall through cleanly
    until we know which channels SIREN wants suppressed for them.
    """
    if particle in ("mu-", "mu+"):
        lines = [
            "/particle/select mu-",
            "/particle/process/inactivate 1",  # Decay
            "/particle/process/inactivate 7",  # muMinusCaptureAtRest
            "/particle/select mu+",
            "/particle/process/inactivate 1",  # Decay
        ]
        return "\n".join(lines) + "\n"
    return ""


def macro_text(material: str, particle: str, energy_mev: int, events: int) -> str:
    """G4 macro for a single (particle, energy) cell. Container-side paths."""
    out = f"/out/{material}/{particle}/{energy_mev}MeV/photonsim.root"
    lines = [
        "# Auto-generated by scan_smax.py — do not hand-edit.",
        f"/output/filename {out}",
        "/run/initialize",
        "/photon/storeIndividual false",
    ]
    decay_block = _decay_disable_block(particle)
    if decay_block:
        lines.extend(decay_block.rstrip().splitlines())
    lines.extend([
        f"/gun/particle {particle}",
        "/gun/randomEnergy false",
        f"/gun/energy {energy_mev} MeV",
        "/gun/position 0 0 0 m",
        "/gun/direction 0 0 1",
        f"/run/beamOn {events}",
    ])
    return "\n".join(lines) + "\n"


def docker_cmd(
    image: str,
    photonsim_dir: Path,
    output_dir: Path,
    macro_container_path: str,
) -> list[str]:
    return [
        "docker", "run", "--rm", "--platform", "linux/amd64",
        "-v", f"{photonsim_dir}:/opt/PhotonSim",
        "-v", f"{output_dir}:/out",
        image,
        "/opt/PhotonSim/build/PhotonSim", macro_container_path,
    ]


def run_cell(
    *,
    material: str,
    particle: str,
    energy_mev: int,
    events: int,
    output_dir: Path,
    photonsim_dir: Path,
    image: str,
    skip_existing: bool,
    dry_run: bool,
) -> tuple[bool, str]:
    cell_dir = output_dir / material / particle / f"{energy_mev}MeV"
    cell_dir.mkdir(parents=True, exist_ok=True)
    root_path = cell_dir / "photonsim.root"
    macro_path = cell_dir / "run.mac"
    log_path = cell_dir / "stdout.log"

    if skip_existing and root_path.exists() and root_path.stat().st_size > 0:
        return True, f"skip (exists): {root_path}"

    macro_path.write_text(macro_text(material, particle, energy_mev, events))

    macro_container_path = f"/out/{material}/{particle}/{energy_mev}MeV/run.mac"
    cmd = docker_cmd(image, photonsim_dir, output_dir, macro_container_path)

    if dry_run:
        return True, "dry-run: " + " ".join(cmd)

    with log_path.open("w") as log:
        log.write(f"$ {' '.join(cmd)}\n\n")
        log.flush()
        proc = subprocess.run(cmd, stdout=log, stderr=subprocess.STDOUT)

    if proc.returncode != 0:
        return False, f"FAILED (rc={proc.returncode}): see {log_path}"
    if not root_path.exists() or root_path.stat().st_size == 0:
        return False, f"FAILED (no ROOT output): see {log_path}"
    return True, f"ok: {root_path} ({root_path.stat().st_size / 1024:.0f} KB)"


def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    p = argparse.ArgumentParser(
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    p.add_argument(
        "--particles", nargs="+", default=["mu-"],
        help="Particle names (default: mu-). Valid: " + ", ".join(sorted(PARTICLES_KNOWN)),
    )
    p.add_argument(
        "--energies", nargs="+", type=int, default=DEFAULT_ENERGIES_MEV,
        help="Kinetic energies in MeV (default: %(default)s).",
    )
    p.add_argument(
        "--material", default="water",
        help="Target material (default: water). Currently only 'water' is honored "
             "by the PhotonSim binary — others reserved for future expansion.",
    )
    p.add_argument(
        "--events", type=int, default=None,
        help="Events per cell. Default: energy-dependent schedule "
             f"({DEFAULT_EVENT_BASE} at/below {DEFAULT_EVENT_ANCHOR_MEV} MeV, "
             f"halved per doubling above, floor {DEFAULT_EVENT_FLOOR}). "
             "Pass an int to force a fixed count for every cell.",
    )
    p.add_argument(
        "--output-dir", type=Path,
        default=Path("/Users/cjesus/Desktop/INTERM/OUTPUT/smax"),
        help="Host output directory (bind-mounted to /out inside container).",
    )
    p.add_argument(
        "--photonsim-dir", type=Path,
        default=Path("/Users/cjesus/Desktop/INTERM/PhotonSim"),
        help="Host PhotonSim checkout (bind-mounted to /opt/PhotonSim).",
    )
    p.add_argument("--image", default="lucid:latest", help="Docker image (default: %(default)s).")
    p.add_argument(
        "--no-skip-existing", action="store_true",
        help="Re-run cells whose photonsim.root already exists (default: skip).",
    )
    p.add_argument("--dry-run", action="store_true", help="Print commands, don't execute.")
    return p.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    args = parse_args(argv)

    bad_particles = set(args.particles) - PARTICLES_KNOWN
    if bad_particles:
        print(f"error: unknown particle(s): {sorted(bad_particles)}", file=sys.stderr)
        print(f"valid: {sorted(PARTICLES_KNOWN)}", file=sys.stderr)
        return 2

    if args.material not in MATERIALS_KNOWN:
        print(f"error: material '{args.material}' not supported yet "
              f"(valid: {sorted(MATERIALS_KNOWN)})", file=sys.stderr)
        return 2

    if shutil.which("docker") is None:
        print("error: docker not on PATH", file=sys.stderr)
        return 2

    if not args.photonsim_dir.exists():
        print(f"error: photonsim-dir does not exist: {args.photonsim_dir}", file=sys.stderr)
        return 2

    args.output_dir.mkdir(parents=True, exist_ok=True)

    cells = [(p, e) for p in args.particles for e in args.energies]
    sched = ("fixed=" + str(args.events)) if args.events is not None else "energy-dependent"
    print(f"scan_smax: {len(cells)} cells "
          f"({len(args.particles)} particles × {len(args.energies)} energies; events: {sched}) "
          f"-> {args.output_dir / args.material}")

    failures: list[str] = []
    for i, (particle, energy) in enumerate(cells, 1):
        events = args.events if args.events is not None else default_events_for(energy)
        label = f"[{i:>3d}/{len(cells)}] {particle:>6s}  {energy:>6d} MeV  ({events:>4d} evt)"
        ok, msg = run_cell(
            material=args.material,
            particle=particle,
            energy_mev=energy,
            events=events,
            output_dir=args.output_dir,
            photonsim_dir=args.photonsim_dir,
            image=args.image,
            skip_existing=not args.no_skip_existing,
            dry_run=args.dry_run,
        )
        print(f"{label}  {msg}")
        if not ok:
            failures.append(label)

    if failures:
        print(f"\n{len(failures)} cell(s) failed:", file=sys.stderr)
        for f in failures:
            print(f"  {f}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
