#!/usr/bin/env python3
"""Generate SIREN-input ROOT files with s/s_max-normalised histograms.

For each (material, particle, energy) cell:
  1. Reads PhotonSim/data/<material>/<particle>/smax_fit.csv (produced by
     tools/smax/analyze_smax.py) — the per-particle fit (form indicated by
     the row's `form` column; currently "A*E^B" or "smooth_two_power").
  2. Evaluates s_max(E_gun) and bakes /output/smax <val> mm into the macro.
  3. Runs PhotonSim. Output ROOT contains the full set of normal
     histograms plus the new PhotonHist_AngleDistanceNorm (angle vs s/s_max).

This is the SIREN-training-input mode; do not confuse with scan_smax.py,
which is the upstream s_max-parametrisation scan.
"""

from __future__ import annotations

import argparse
import csv
import shutil
import subprocess
import sys
from pathlib import Path


PARTICLES_KNOWN = {"mu-", "mu+", "e-", "e+", "pi+", "pi-", "gamma", "proton"}
MATERIALS_KNOWN = {"water"}
DEFAULT_ENERGIES_MEV = [100, 200, 500, 1000, 2000, 5000, 10000]
DEFAULT_DATA_DIR = Path(__file__).resolve().parents[1] / "data"


def load_smax_row(material: str, particle: str, data_dir: Path) -> tuple[dict, int]:
    """Return (csv_row_dict, fit_min_mev) from smax_fit.csv. Errors if missing."""
    path = data_dir / material / particle / "smax_fit.csv"
    if not path.exists():
        raise FileNotFoundError(
            f"No parametrisation at {path}. Run tools/smax/analyze_smax.py first."
        )
    with path.open() as fh:
        reader = csv.DictReader(fh)
        row = next(reader, None)
    if row is None or not row.get("form"):
        raise ValueError(f"Parametrisation at {path} is empty/incomplete.")
    return row, int(row["fit_min_mev"])


def smax_at(row: dict, energy_mev: int) -> float:
    """Evaluate s_max(E) for a CSV row.  Keep in sync with the eval branches
    in PhotonSim/tools/smax/analyze_smax.py (canonical source) and the
    consumer shims in LUCiD's siren_inputs/generate_jobs.py + build_tables.py.
    """
    form = row["form"]
    if form == "A*E^B":
        A, B = float(row["A"]), float(row["B"])
        return A * energy_mev ** B
    if form == "smooth_two_power":
        a, b1, b2, E0 = (float(row[k]) for k in ("a", "b1", "b2", "E0"))
        return a * energy_mev ** b1 / (1.0 + (energy_mev / E0) ** (b1 - b2))
    if form == "piecewise":
        ej = float(row["e_join_mev"])
        if energy_mev < ej:
            a, b1, b2, E0 = (float(row[k]) for k in ("a", "b1", "b2", "E0"))
        else:
            a, b1, b2, E0 = (float(row[k]) for k in ("a_hi", "b1_hi", "b2_hi", "E0_hi"))
        return a * energy_mev ** b1 / (1.0 + (energy_mev / E0) ** (b1 - b2))
    raise ValueError(f"unknown smax form: {form!r}")


def macro_text(material: str, particle: str, energy_mev: int,
               events: int, smax_mm: float) -> str:
    """G4 macro for a single SIREN-input cell. Container-side paths."""
    out = f"/out/{material}/{particle}/{energy_mev}MeV/photonsim.root"
    lines = [
        "# Auto-generated by scan_siren_inputs.py — do not hand-edit.",
        f"/output/filename {out}",
        f"/output/smax {smax_mm:.6f} mm",
        "/run/initialize",
        "/photon/storeIndividual false",
    ]
    if particle in ("mu-", "mu+"):
        lines.extend([
            "/particle/select mu-",
            "/particle/process/inactivate 1",
            "/particle/process/inactivate 7",
            "/particle/select mu+",
            "/particle/process/inactivate 1",
        ])
    lines.extend([
        f"/gun/particle {particle}",
        "/gun/randomEnergy false",
        f"/gun/energy {energy_mev} MeV",
        "/gun/position 0 0 0 m",
        "/gun/direction 0 0 1",
        f"/run/beamOn {events}",
    ])
    return "\n".join(lines) + "\n"


def run_cell(*, material: str, particle: str, energy_mev: int, events: int,
             smax_mm: float, output_dir: Path, photonsim_dir: Path,
             image: str, skip_existing: bool, dry_run: bool) -> tuple[bool, str]:
    cell_dir = output_dir / material / particle / f"{energy_mev}MeV"
    cell_dir.mkdir(parents=True, exist_ok=True)
    root_path = cell_dir / "photonsim.root"
    macro_path = cell_dir / "run.mac"
    log_path = cell_dir / "stdout.log"

    if skip_existing and root_path.exists() and root_path.stat().st_size > 0:
        return True, f"skip (exists): {root_path}"

    macro_path.write_text(macro_text(material, particle, energy_mev, events, smax_mm))
    macro_container_path = f"/out/{material}/{particle}/{energy_mev}MeV/run.mac"
    cmd = [
        "docker", "run", "--rm", "--platform", "linux/amd64",
        "-v", f"{photonsim_dir}:/opt/PhotonSim",
        "-v", f"{output_dir}:/out",
        image,
        "/opt/PhotonSim/build/PhotonSim", macro_container_path,
    ]

    if dry_run:
        return True, "dry-run: " + " ".join(cmd)

    with log_path.open("w") as log:
        log.write(f"$ {' '.join(cmd)}\n\n")
        log.flush()
        proc = subprocess.run(cmd, stdout=log, stderr=subprocess.STDOUT)
    if proc.returncode != 0:
        return False, f"FAILED (rc={proc.returncode}): see {log_path}"
    if not root_path.exists() or root_path.stat().st_size == 0:
        return False, f"FAILED (no ROOT output): see {log_path}"
    return True, (f"ok: {root_path} ({root_path.stat().st_size / 1024:.0f} KB, "
                  f"s_max={smax_mm:.0f} mm)")


def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    p = argparse.ArgumentParser(description=__doc__,
                                formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("--particles", nargs="+", required=True,
                   help=f"Valid: {sorted(PARTICLES_KNOWN)}")
    p.add_argument("--energies", nargs="+", type=int, default=DEFAULT_ENERGIES_MEV,
                   help="Kinetic energies in MeV (default: %(default)s).")
    p.add_argument("--material", default="water",
                   help=f"Default: water. Valid: {sorted(MATERIALS_KNOWN)}.")
    p.add_argument("--events", type=int, default=50,
                   help="Events per cell (default: 50). SIREN training "
                        "typically wants more than a parametrisation scan.")
    p.add_argument("--output-dir", type=Path,
                   default=Path("/Users/cjesus/Desktop/INTERM/OUTPUT/siren_inputs"),
                   help="Host output directory.")
    p.add_argument("--data-dir", type=Path, default=DEFAULT_DATA_DIR,
                   help="Where to read smax_fit.csv from (default: PhotonSim/data).")
    p.add_argument("--photonsim-dir", type=Path,
                   default=Path("/Users/cjesus/Desktop/INTERM/PhotonSim"))
    p.add_argument("--image", default="lucid:latest")
    p.add_argument("--no-skip-existing", action="store_true")
    p.add_argument("--dry-run", action="store_true")
    p.add_argument("--ignore-fit-threshold", action="store_true",
                   help="Allow energies below the fit's fit_min_mev. Default: "
                        "skip with a warning, since s_max there is extrapolated.")
    return p.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    args = parse_args(argv)

    bad = set(args.particles) - PARTICLES_KNOWN
    if bad:
        print(f"error: unknown particles {sorted(bad)}", file=sys.stderr)
        return 2
    if args.material not in MATERIALS_KNOWN:
        print(f"error: material '{args.material}' not supported", file=sys.stderr)
        return 2
    if shutil.which("docker") is None:
        print("error: docker not on PATH", file=sys.stderr)
        return 2

    args.output_dir.mkdir(parents=True, exist_ok=True)

    fits: dict[str, tuple[dict, int]] = {}
    for particle in args.particles:
        try:
            fits[particle] = load_smax_row(args.material, particle, args.data_dir)
        except (FileNotFoundError, ValueError) as exc:
            print(f"error: {exc}", file=sys.stderr)
            return 2

    cells = [(p, e) for p in args.particles for e in args.energies]
    print(f"scan_siren_inputs: {len(cells)} cells "
          f"({len(args.particles)} particles × {len(args.energies)} energies × "
          f"{args.events} events) -> {args.output_dir / args.material}")

    failures: list[str] = []
    for i, (particle, energy) in enumerate(cells, 1):
        row, fit_min = fits[particle]
        below_fit = energy < fit_min
        if below_fit and not args.ignore_fit_threshold:
            print(f"[{i:>3d}/{len(cells)}] {particle:>6s}  {energy:>6d} MeV  "
                  f"SKIP (E < fit_min={fit_min} MeV; pass --ignore-fit-threshold to force)")
            continue
        smax = smax_at(row, energy)
        label = (f"[{i:>3d}/{len(cells)}] {particle:>6s}  {energy:>6d} MeV "
                 f"({args.events:>3d} evt, s_max={smax:>7.0f} mm"
                 f"{', extrap' if below_fit else ''})")
        ok, msg = run_cell(
            material=args.material,
            particle=particle,
            energy_mev=energy,
            events=args.events,
            smax_mm=smax,
            output_dir=args.output_dir,
            photonsim_dir=args.photonsim_dir,
            image=args.image,
            skip_existing=not args.no_skip_existing,
            dry_run=args.dry_run,
        )
        print(f"{label}  {msg}")
        if not ok:
            failures.append(label)

    if failures:
        print(f"\n{len(failures)} cell(s) failed:", file=sys.stderr)
        for f in failures:
            print(f"  {f}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
