# Macro for 50 muons with individual photon information

# Set output filename before initialization
/output/filename elec_gun_1000_MeV_100_events_fixed_energy.root

/run/initialize

# Enable individual photon storage to capture photon information
/photon/storeIndividual true
/edep/storeIndividual false

# Set up primary particle with random energy
/gun/particle e-
/gun/randomEnergy false
/gun/energy 1000 MeV
/gun/position 0 0 0 m
/gun/direction 0 0 1

# Run 50 events
/run/beamOn 100